

baseURL = "https://isnet-series.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "ISNET Series Website"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"
staticDir = "static"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
enableGitInfo = true

[Params]

    # Souce Code repository section
    description = "The online knowledge base of the Information and Statistics in Nuclear Experiment and Theory (ISNET) series"
    github_repository = "https://github.com/isnet-series/isnet-series.github.io"
    version = ""

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]

# Global menu section
# [[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1

#[[menu.main]]
#    name = "Meetings"
#    url = "https://twitter.com/thingsym"
#    weight = 2

#[[menu.main]]
#    name = "Resources"
#    url = "https://twitter.com/thingsym"
#    weight = 3

#[[menu.main]]
#    name = "JPhysG Issues"
#    url = "https://twitter.com/thingsym"
#    weight = 4
